name: Update problem list
on:
  schedule:
    - cron:  '0 0 ? ? 1'
jobs:
  update_and_commit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Export the latest list
        run: python -m leetcode-sorter --include-paid-only --csv_path new.csv
      - uses: actions/checkout@v2.3.1
        with:
          clean: no
          ref: web
      - name: Update the list
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mv new.csv static/list.csv
          git add static/list.csv
          git commit -m "Update problem list. $(date)"
          git push
